fix: 명함 만들기 뷰 새로고침 버튼 변경(#617)
TeamNADA/NADA-iOS-ForRelease pull request #620
Opened 2023-10-09 06:40 UTC by hyun99999

## 🌴 PR 요약

🌱 작업한 브랜치
- #617

🌱 작업한 내용
- 새로고침 버튼이 변경되어서 이미지 에셋을 변경하였습니다.
- 다크모드용 이미지 에셋도 추가하였습니다.
- highlighted 될 때를 설정하였습니다.

### 🚨 트러블..
- tap 했을 때 UIButton.State 는 설정할 수 없던거 같습니다.. 혹시 방법을 알고 계신지요..!
- 빠르게 탭 형식의 동작에는 이미지가 안바뀌고 버튼을 꾹 터치하면 바뀌고 있습니다..

## 📸 스크린샷
|기능|스크린샷|
|:--:|:--:|
|버튼 변경|<img src="https://github.com/TeamNADA/NADA-iOS-ForRelease/assets/69136340/2541017e-ab52-4944-a1b6-e9cdd1cce262" width ="200">|

## 📮 관련 이슈
- Resolved: #617

2023-10-13 08:52 UTC, yj607 requested changes
현규야 잘 좀 해봐;;

2023-10-25 12:15 UTC, dlwns33 approved these changes

2023-10-25 12:15 UTC, dlwns33 commented on NADA-iOS-forRelease/Sources/Cells/CreationCard/BackCardCreationCollectionViewCell.swift
> +        refreshButton.setBackgroundImage(UIImage(named: "icnHoverRandom"), for: .highlighted)
혹시 tap 했을때 UIButton.State 가 안바뀐다는게 isSelected가 바뀌지 않는 뜻인가용?! 
tap했을때 버튼의 이미지를 바꾸고 싶은것이죠?
탭할때 버튼의 state를 한번 print해봐야될 것 같아요 그냥 저희 button isSelected 바꿀때 처럼 하면 되는걸로 알고있어요.!

2023-10-25 12:27 UTC, hyun99999 commented on NADA-iOS-forRelease/Sources/Cells/CreationCard/BackCardCreationCollectionViewCell.swift
> +        refreshButton.setBackgroundImage(UIImage(named: "icnHoverRandom"), for: .highlighted)
selected state 설정해줬는데 안되더라구요...

2023-10-25 12:28 UTC, dlwns33 commented on NADA-iOS-forRelease/Sources/Cells/CreationCard/BackCardCreationCollectionViewCell.swift
> +        refreshButton.setBackgroundImage(UIImage(named: "icnHoverRandom"), for: .highlighted)
흠냐링.. 요거 저두 한번 풀받아서 봐볼게요!

2023-10-26 04:54 UTC, yj607 approved these changes
이거 맞나 일단 자유형 갈겨봄 🏊‍♀️

2023-10-27 15:57 UTC, hyun99999 commented
이부분 머지하고 qa 기간에 좀 손봐보겠습니다!

2023-10-27 15:57 UTC, merged